### ISSUE TITLE
Typs in Python Getting Started?

### ISSUE THREAD

**Issue by clayop** [steemit/devportal#1]
https://github.com/steemit/devportal/edit/master/_python/getting_started.md
```
 Install with python-steem:

$ sudo apt-get install libffi-dev libssl-dev python-dev
$ python-steem3 install steem
```

I think this should be

```
Install with pip:

$ sudo apt-get install libffi-dev libssl-dev python-dev python3-pip
$ pip3 install steem
```

**Comment by mcifani** [comment]
Thanks @clayop for the suggestions, we'll get them incorporated as they will be helpful for new developers.

**Comment by clayop** [comment]
See here: https://github.com/xeroc/python-steem/blob/master/README.md

Original repo is updated as I made correction.
