### ISSUE TITLE
Main Nav Management

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal#101]
The Main Nav on the site keeps growing. We need a way to manage its vertical height.

Implement a collapsible nav. Where each section (eg QUICKSTART, COMMUNITY) can be collapsed.

**AC**
- [x] Sections are collapsed by default
- [x] Sections can be expanded on click
- [x] Currently viewed section is expanded automatically when on that section's page.
- [ ] Auto expansion of different sections on the same page would be nice but is not required.

**Comment by ayipeciaceh** [comment]
Good
