### ISSUE TITLE
Appbase condenser_api.* calls are missing query parameters

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal#107]
The `condenser_api.*` section of our appbase api definitions page is missing the query parameter definitions. Our rake task for filling these out uses `jsonrpc.get_signatures`; the root cause may be there.

Regardless, our api definition needs to be complete. Take the _fastest_ approach to filling in the api arguments.

**AC**
- [x] condenser_api.* methods have their query parameters completely enumerated in the same manner as the others.

**Comment by inertia186** [comment]
a4db42181ee02922f865e7df38aab2e3e45e2c23
