### ISSUE TITLE
Simplify Community Main Nav and add to list of resources

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal#110]
We want to add to the list of 3rd party libraries and tools, but a full listing would/could get pretty onerous from a UI perspective. 

**AC**
- [x] Collapse 3rd party tools to one menu item
- [x] Try out and add as many high quality 3rd party libs as possible (aim for tripling the current count)
For each item
- [x] Provide an accurate description of the lib, including purpose, language, os, and utility as appropriate
- [x] Provide a link to the lib, app, resource

**Comment by inertia186** [comment]
Might be slightly out of date, but here's where I used to maintain known API Libraries.  Probably only half of them still work: https://www.steem.center/index.php?title=API_Libraries

**Comment by feruzm** [comment]
Libraries and Dev helpers (3rd party swaggers, documentations, bash scripts, command line tools, etc.) I would suggest we make this as a spike to agree on list, compile list first...
