### ISSUE TITLE
Recipe: How to read forum/market bandwidth

### ISSUE THREAD

**Issue by inertia186** [steemit/devportal#119]
Currently, we document how to read raw bandwidth data from the blockchain:

https://developers.steem.io/apidefinitions/#apidefinitions-witness-api
https://developers.steem.io/apidefinitions/#condenser_api.get_account_bandwidth

We should add more detail on how to process the raw data so that it can be presented like steemd.com as a percentage available.

- [x] *"As an app developer; I want to understand the raw bandwidth data; so that I can present it in a more useful manner."*
  - [ ] ~- option - decide if this could also be a full tutorial in a particular language~ the calculation is language agnostic
  - [x] link from api definitions on`witness_api` and `condenser_api` to this recipe

**Comment by relativityboy** [comment]
We may deprioritize this story based on HF20 features.
