### ISSUE TITLE
Node-T: Improve Steem node sync performance

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal#126]
User: I wanna sync my node fast!

Steem Nodes can take a long time to catch up to the most current block when getting blocks P2P. The block_log can be used to bring a node up to speed much more quickly.

**AC**
- [x] tutorial showing how to sync a node using a block_log file
- [x] add 'improve replay performance' recommendations.
- [x] optional - location of the most current file hosted by steemit and it's approx size.

**Comment by relativityboy** [comment]
Waiting on authoritative instructions.

**Comment by relativityboy** [comment]
We should followup with @jredbeard about the public url for steemit's BL, and associated information to keep/get it up to date.

**Comment by feruzm** [comment]
@relativityboy self assigned, should I work on this or take another one?
