### ISSUE TITLE
Tutorial Images

### ISSUE THREAD

**Issue by inertia186** [steemit/devportal#132]
We have several images being hosted on `steemitimages.com`.  There's 25 of these in `master` so far.  They should be hosted by devportal instead.

For example, `_tutorials-javascript/client-signing.md` references a `steemitimages.com` image that should live in `images/tutorials-javascript/client-signing` instead.

This also implies that devportal-tutorials-js avoid `steemitimages.com`.
All images hosted on `steemitimages.com` are now hosted somewhere in `images` of devportal-tutorials-js. 

**AC**

- [x] Link tutorial pages images to those hosted in the appropriate repo

**Comment by relativityboy** [comment]
@roboza - there's no PR associated with this issue. It should not be in review.

**Comment by roboza** [comment]
PR #152

**Comment by relativityboy** [comment]
@roboza this why our standard practice is to put `Closes #storynumber` in the PR. That needs to be done or the issues will get kicked back to in-progress every time.
