### ISSUE TITLE
Create Python Stories

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal#142]
This should be as close as possible to the Javascript set of tutorials

**AC**
- [x] a list of python stories to take developers from curious to competent in a comment called **Results**

**Comment by feruzm** [comment]
**Results**

We have list of tutorials for JS: https://github.com/steemit/devportal/issues/40#issuecomment-376261025, following list is almost identical with minor additions

1. Get post list from different category (trending, hot, active, etc.), print object/json
2. Get post content and details with permlink and author
3. Get voters list on post/comment, print list
4. Get comments of post
5. Get comments of account
6. Get replies of account
7. Using keys and authorities with steem-python
8. Submit a post
9. Submit a comment/reply
10. Edit post/comment/reply using diff_match_patch.
11. Reblogging post.
12. Search accounts and tags
13. Vote post/comment (upvote, downvote)
14. Get followers and followings list of user
15. Follow another user (follow, unfollow)
16. Interpreting/get account reputation
17. Claim rewards
18. Transfer STEEM and SBD
19. Power up STEEM
20. Transfer STEEM and SBD to savings balance
21. Convert SBD to STEEM
22. Power down STEEM
23. Witness listing/voting/unvoting
24. Delegate STEEM POWER
25. Get delegations by user
26. Stream operations/transactions/blocks
27. Grant posting permission to another account (social activity)
28. Grant active permission to another account (funds activity)
29. Account recovery process
30. Account Password/Private key change

**Comment by relativityboy** [comment]
> Get post list from different category
`category` should probably be `tag` or `filter` depending on which one you're talking about.

Overall though, LTGM.
