### ISSUE TITLE
More in-depth Steemconnect OAuth-2 description

### ISSUE THREAD

**Issue by feruzm** [steemit/devportal#151]
How and why Steemconnect was implemented, what are the advantages of using it? How Steem auth works and why oauth-2 was proposed, etc? 
>https://github.com/steemit/steemconnect/wiki/OAuth-2#code-authorization-flow

Answer to these questions can be documented under Services section with Steemconnect page on developers.steem.io

**AC**
- [x] update (as needed) the resource at https://github.com/steemit/steemconnect/wiki/OAuth-2#code-authorization-flow
- [x] create a location on the devportal with introductory text, and then a link to the above resource.
- [x] link to resources documented in #150 (if 150 is completed 1st)

**Comment by relativityboy** [comment]
Proposed **AC**
- [ ] update (as needed) the resource at https://github.com/steemit/steemconnect/wiki/OAuth-2#code-authorization-flow
- [ ] create a location on the devportal with introductory text, and then a link to the above resource.
