### ISSUE TITLE
Jussi Documentation

### ISSUE THREAD

**Issue by inertia186** [steemit/devportal#153]
We need to document `jussi`.  Both setting up a node that responds to `jussi` requests and some information on which api namespaces sit in front of the various related upstreams.

**AC**

- [x] tutorial on how to set up a jussi node
- [x] how to use jussi to direct different API calls to different upstreams
- [x] page that lists how api namespaces benefit from jussi

**Comment by TimCliff** [comment]
It would be beneficial to also include information on how to use jussi to direct different API calls to different servers.

**Comment by bnchdrff** [comment]
@gl2748 and i wrote this https://steemit.com/steemdev/@maitland/running-condenser-jussi-and-a-new-service-locally-adding-feature-flags-to-condenser

**Comment by inertia186** [comment]
It doesn't look like we have a default configuration yet.  Ideally, we should be able to kick off a local instance with:

```bash
git clone https://github.com/steemit/jussi.git
cd jussi
docker build -t="$USER/jussi:$(git rev-parse --abbrev-ref HEAD)" .
docker run -itp 9000:8080 "$USER/jussi:$(git rev-parse --abbrev-ref HEAD)"
```

Looking at these issues, I can get it to work:

https://github.com/steemit/jussi/issues/143
https://github.com/steemit/jussi/issues/103

My `diff` ended up being:

```diff
diff --git a/Dockerfile b/Dockerfile
index c6d15db..2ad9374 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -21,7 +21,7 @@ ENV APP_CMD jussi.serve
 ENV JUSSI_SERVER_HOST 0.0.0.0
 ENV JUSSI_SERVER_PORT 9000
 ENV JUSSI_UPSTREAM_CONFIG_FILE ${APP_ROOT}/PROD_UPSTREAM_CONFIG.json
-ENV JUSSI_TEST_UPSTREAM_URLS True
+ENV JUSSI_TEST_UPSTREAM_URLS False

 # all nginx env vars must also be changed in service/nginx/nginx.conf
 ENV NGINX_SERVER_PORT 8080
diff --git a/PROD_UPSTREAM_CONFIG.json b/PROD_UPSTREAM_CONFIG.json
index 1b3967c..24f3a86 100644
--- a/PROD_UPSTREAM_CONFIG.json
+++ b/PROD_UPSTREAM_CONFIG.json
@@ -5,7 +5,7 @@
     "urls": [
       [
         "steemd",
-        "wss://steemd.steemit.com"
+        "wss://steemd-int.steemit.com"
       ]
     ],
     "ttls": [
```

I don't think we should have a `diff` on devportal, though.  So I consider this issue blocked.

**Comment by relativityboy** [comment]
@john-g-g how does this look to you?

**Comment by inertia186** [comment]
Unblocked by https://github.com/steemit/jussi/commit/bb1710e87ab95ad0cf0d1243539cbab818cbfdef.
