### ISSUE TITLE
Calculate the value of an upvote

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal#157]
Originally submitted as steemit/devportal-tutorials-js#65 by @roadscape 

As a dev, I want to know how to calculate the value of a 100% upvote for a given user.

**AC**
- [x] Tutorial goes from Zero->100
- [x] Description of how to get user's account info, or point to tutorial that shows same
- [x] Description of everything in the environment that goes into calculating a user's current upvote value, in an abstract way.
- [ ] At least 2 specific examples

**Comment by feruzm** [comment]
recipes?! https://github.com/steemit/steempunks/issues/343

**Comment by feruzm** [comment]
@relativityboy could you please review this https://github.com/steemit/devportal/pull/172 and let me know if it needs some additions? Thanks

**Comment by inertia186** [comment]
Do you think it would be a good idea to explain `voting_power`+ recharge in the interval since last post?

I'm talking about determining the `power` value:

https://github.com/steemit/devportal/commit/34e3350c5ad60922d72ec23c89047596367b7eea#diff-4362d2f6eaf572d5b6fd3cdd9686a236R23
