### ISSUE TITLE
Additional terms to be added to glossary

### ISSUE THREAD

**Issue by roboza** [steemit/devportal#158]
After working on the get_active_votes tutorial it came to my attention that we need to add some more terms to the glossary Here are a few to be considered:

* `voter` - The author account name of the vote.
* `weight` - Weight of the voting power.
* `rshares` - Reward shares.
* `percent` - Percent of vote.
* `time` - Time the vote was submitted.

Some that might need more clarification:

* `reputation`

Links of interest:

https://steemit.com/steemdev/@jfollas/write-a-steemit-web-app-part-13-how-to-calculate-a-vote-s-rshares

**Comment by inertia186** [comment]
Maybe we can slip these in too: #91
