### ISSUE TITLE
Update 'Readme' Structure Spec for Tutorials & Recipes

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal#159]
The tutorial guidleines in steemit/devportal#46 are very good, but as the devportal and tutorials evolve, we may need a different standard that extends the description in `46` and leverages some of our new infrastructure. 

*This story does not attempt to address the filesystem of a tutorial*

**AC**
- [x] Create an updated set of guidelines that are readily followable by developers creating tutorials, and optimizes both consumer understanding and development effort.
- [x] Results are in a comment on this issue titled **Results**
- [x] All Steemworks developers agree to the approach

**Comment by feruzm** [comment]
I like the structure, this might require us revisiting all previous tutorial readmes and updating them in next sprint

**Comment by inertia186** [comment]
I think @feruzm has a point.  If a tutorial is essentially and fundamentally a "child" (or extension) of a previous "parent" tutorial, it can include a link to that previous tutorial and only use this simplified structure.  One addition I would recommend in the simplified structure is to have a structure of all related "child" tutorials under that topical umbrella, e.g.:

* How to query a widget (parent) `<- links to tutorial`
  * How to query a widget with thingys (child) `<- links to tutorial`
  * How to query a thingy that has certain widgets (child) `<- links to tutorial`
  * How to query a widget that does a whooza on thingys (child) `<- current tutorial, does not link`
  * How to query a widgets grouped by whoozas (child) `<- links to tutorial`

**Comment by relativityboy** [comment]
@inertia186 - Linking a to a previous 'parent tutorial' is in essence describing the current tutorial as a `complication` from your original guidelines. If the complication is large enough, what y'all describe is jess fine.

@feruzm the structure you propose is illustrated nicely in [JS-08])(https://github.com/steemit/devportal-tutorials-js/tree/master/tutorials/08_get_account_replies). While an improvement over earlier tutorials, I think it leaves some gaps. I'll cook up a branch with some examples of my proposal as soon as I'm able. That will give us firmer ground to discuss.

**Comment by feruzm** [comment]
I like new structure more, Intro combines purpose and description and directly into steps within tutorial...

**Comment by relativityboy** [comment]
Ok, final version is here https://github.com/steemit/devportal-tutorials-js/blob/master/tutorials/tutorial_structure.md
