### ISSUE TITLE
Add busyorg steem-api

### ISSUE THREAD

**Issue by TimCliff** [steemit/devportal#167]
In the condenser/steemit.com FAQ, it is listing https://steemit.com/steemjs/@fabien/steem-api-now-released as one of the tools available to developers. This information should be integrated into the devportal, so we can point developers there as the central source of information.

It references this repository:
https://github.com/busyorg/steem-api

The appropriate place to put it seems to be:
https://developers.steem.io/community/#community-resources

tagging @bonustrack - thoughts?

**Comment by bonustrack** [comment]
Yes, this service can be helpful for developers, i'm using it almost everyday to check data. Busy.org maintain it so it should fit well here as Tim suggested: https://developers.steem.io/community/#community-resources

There is also this page that may help: https://steemconnect.com/docs/steemjs we list here all steem.js methods with a link to `steem-api` (the "Try it" links) for check results.
