### ISSUE TITLE
Update API Definitions comment related operations (and tutorials).

### ISSUE THREAD

**Issue by inertia186** [steemit/devportal#174]
*As an application developer, I want to know everything related to `comment` operation, so that I can broadcast content that correctly reflects my intent.*

The API Definitions `comment` broadcast operation lacks details on broadcasting content (post/comment).  This op needs to enumerate the params that are allowed, what values can be passed, and what related operations can be included in the same transaction and why.

See: https://developers.steem.io/apidefinitions/#broadcast_ops_comment

**AC**

- [x] comment operations have complete details
- [ ] ~related tutorials that affect comment operations link to the comment broadcast op~

Second AC removed in favor of putting that work within steemit/devportal-tutorials-js#82

**Comment by roboza** [comment]
I have blocked this until https://github.com/steemit/devportal-tutorials-js/commit/e7f92d796bd2f024a1a7a22a0b4706ce7a2e2407 is merged into develop then will create branch corresponding to this issue to add links to devportal @relativityboy @inertia186 @feruzm

**Comment by relativityboy** [comment]
@roboza - That would be a very brittle way to ad those links. I've created steemit/devportal-tutorials-js#82 to take care of them.
