### ISSUE TITLE
Tutorial suggestion - How to get a list of user's posts in latest to oldest order?

### ISSUE THREAD

**Issue by TimCliff** [steemit/devportal#184]
For a website operator, getting a list of blog posts from a specific user would be a useful example to have.

**Comment by feruzm** [comment]
That's very first tutorial: 
https://developers.steem.io/tutorials-javascript/blog_feed 
source code: 
https://github.com/steemit/devportal-tutorials-js/tree/master/tutorials/01_blog_feed

**Comment by TimCliff** [comment]
:facepalm: missed that. Thanks!
