### ISSUE TITLE
Deploy 1 - Raked JS-T, Ruby Tutorials

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal#205]
```
Our first tracked deployment.
```
* New RB Tutorials
* New JS Tutorials
* All JS tutorials are pulled from the [devportal-tutorials-js](/steemit/devportal-tutorials-js) repository

**Comment by roboza** [comment]
@relativityboy 

Error on https://developers.steem.io/tutorials-javascript/get_posts - Missing image
The image is still pointing to github, I think we spoke before about hosting these images in the devportal repo so that if users cloned and worked offline things would still work

**Comment by relativityboy** [comment]
@roboza - thanks.

What we decided was to move the images into their respective code repos, and  *out* of the devportal. This looks like an issue with the rake task.

**Comment by relativityboy** [comment]
Not bad for a 1st run. We'll leave it up.
