### ISSUE TITLE
Navigation menu on mobile

### ISSUE THREAD

**Issue by kareniel** [steemit/devportal#207]
Hi! :)

I noticed while using the website on my phone that it wasn't possible to view the navigation menu.
I think it simply disappears after one of the breakpoints, with no way to display it again. There's also a specific point (700px) where the layout breaks a bit. It shouldn't be a big change but it does involve deciding on how that menu should work. A hamburger icon with a full-width menu coming in from the top should do the trick. Maybe you have a better idea? 

Let me know if you want a PR for this. ❤️ 

ps: the repo link points to https://steemit.github.io/devportal but I think it should (correct me if I'm wrong!) point to https://developers.steem.io

**Comment by RenaudGagne** [comment]
I want to try fixing this.

**Comment by oxarbitrage** [comment]
was going to open an issue for this: 

> ps: the repo link points to https://steemit.github.io/devportal but I think it should (correct me if I'm wrong!) point to https://developers.steem.io

https://steemit.github.io/devportal is broken.

**Comment by relativityboy** [comment]
Thanks @kareniel - we've added it to our backlog and will take a look at it soon. If the effort requires design work it's likely we'll close this issue and open another one that's not labeled as `bug`. We'll be sure to reference this issue so you can watch it.

If you can add some screenshots here of layout breakage that would help us (I know it can feel like a pain, but it really does help.)

**Comment by kareniel** [comment]
@relativityboy Sure!

Here's at 700px:
![screenshot 2018-06-06 13 23 06](https://user-images.githubusercontent.com/419946/41054626-dc07bcb6-698c-11e8-8f45-f99e5cc3a063.png)

And here's at lower than 700px:
![screenshot 2018-06-06 13 23 14](https://user-images.githubusercontent.com/419946/41054625-dbf7c59a-698c-11e8-8cea-958687e70a1e.png)

Here's a gif too if that helps:
![2018-06-06 13 27 40](https://user-images.githubusercontent.com/419946/41054829-7c2507da-698d-11e8-8698-cb339f270d0b.gif)

**Comment by relativityboy** [comment]
@roboza @inertia186 @feruzm - before we work this, we should have a formal spike about what we want to do with "right code" #214

**Comment by relativityboy** [comment]
# blocked by

* #224
