### ISSUE TITLE
DP: Missing image in tutorials-javascript/get_posts

### ISSUE THREAD

**Issue by roboza** [steemit/devportal#212]
Error on https://developers.steem.io/tutorials-javascript/get_posts - Missing image

The image is still pointing to github, I think we spoke before about hosting these images in the devportal repo so that if users cloned and worked offline things would still work

_AC_

- [ ] Image is loading properly

**Comment by relativityboy** [comment]
This looks like a possible issue with the rake parser. @inertia186 

The url as parsed https://github.com/steemit/devportal-tutorials-js/blob/master/tutorials/04_get_posts/Step-01-UI.png?raw=true

The correct url https://raw.githubusercontent.com/steemit/devportal-tutorials-js/master/tutorials/04_get_posts/images/Step-01-UI.png

The raw readme file https://raw.githubusercontent.com/steemit/devportal-tutorials-js/master/tutorials/04_get_posts/README.md

The line we care about is 
```
![Step-01-UI.png](images/Step-01-UI.png)
```
