### ISSUE TITLE
Decide what to do about right-code

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal#214]
As a dev, I want the code to present itself in a consistent and easily understandable way

**AC**
- [ ] decision about whether to keep right code on the dp or not in a comment labeled `#Results`
- [ ] if the decision is made to eliminate it - to when it should be, before, or after we've migrated all 'src' for tutorials to their own repos.

**Comment by inertia186** [comment]
I think pages that need code examples but are not imported by `rake` should continue to use the right-code sections.

**Comment by relativityboy** [comment]
# Results
* After a discussion with @feruzm @inertia186 in a post standup breakout today the decision was made to eliminate right code.
* We'll remove it after we've migrated python and ruby tutorial src out of devportal .
