### ISSUE TITLE
DP: Eval & add Java SC2 lib to community section

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal#225]
Consider adding this lib to communities section
https://github.com/marvin-we/sc2-sdk4j

**AC**
- [x] lib is evaluated for addition.
- [x] Lib is added, or not. If not, comment titled `# Results` explaining why

**Comment by feruzm** [comment]
# Results

Library mention in this issue, is empty repository (https://github.com/marvin-we/sc2-sdk4j).

I did evaluate alternative Java library which is what we are looking for and this does look functional library and actively being developed. I would consider adding this library. https://github.com/hapramp/steemconnect4j

**Comment by relativityboy** [comment]
#236 created to track eval of the steemconnect4j lib. Closing this one.
