### ISSUE TITLE
DP: Rake: Add Rake tasks for -py -rb -* repos

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal#226]
Model after #163

**AC**
- [x] task for https://github.com/steemit/devportal-tutorials-py 
- [x] task for https://github.com/steemit/devportal-tutorials-rb
- [x] task for updating py, rb, js in one command

**Comment by inertia186** [comment]
Blocked because [steemit/devportal-tutorials-py](https://github.com/steemit/devportal-tutorials-py) and [steemit/devportal-tutorials-rb](https://github.com/steemit/devportal-tutorials-rb) are private repos.

The rake task needs them to be public repos.

**Comment by inertia186** [comment]
I've committed what I have so far, to the point of being blocked.

**Comment by relativityboy** [comment]
Blocked makes sense. Shouldn't be in review if it's not been tested & ready to go.

**Comment by relativityboy** [comment]
@inertia186 both repos are now public.
