### ISSUE TITLE
Incorporate and/or update 

### ISSUE THREAD

**Issue by feruzm** [steemit/devportal#231]
Evaluate following documentation and incorporate into devportal or update it

https://steemit.github.io/steemit-docs/#introduction

**Comment by relativityboy** [comment]
@feruzm as of this comment, doesn't look like it's been updated since 2016.

**Comment by feruzm** [comment]
Yes, we can take it down and also consider improving our SEO for devportal... right now it is good, i think another spike to review for keywords would be good, imo.
Image attached:

<img width="1007" alt="screen shot 2018-06-18 at 17 51 42" src="https://user-images.githubusercontent.com/3015990/41543875-72ad0012-7320-11e8-977c-12f7a9370e07.png">

**Comment by inertia186** [comment]
I really think that's all we need to consider, SEO.  There's nothing all that special about steemit-docs right now.  It looks great on the surface, but if people are looking for specific API documentation, maybe if they land anywhere on https://steemit.github.io/steemit-docs/, it should then redirect to https://developers.steem.io/apidefinitions/, and we're done.

**Comment by relativityboy** [comment]
Once we get input from @roboza we'll create an action story.

**Comment by feruzm** [comment]
This is concluded iirc, we are waiting action from @jredbeard to disable Github Pages from archived/removed repo. Notified him!

**Comment by relativityboy** [comment]
Looks like it got taken care of, but not added to review. Closing.
