### ISSUE TITLE
DP: Rake: Imports should chop redundant readme content from tutorial page

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal#234]
As a dev on a given tutorial page, I don't need to see the same thing twice.
(badness in red below)
<img width="716" alt="screen shot 2018-06-19 at 5 12 43 pm" src="https://user-images.githubusercontent.com/599528/41627038-3fffa52e-73e4-11e8-8f0d-c389a2d18d29.png">

**AC**
- [x] tutorial pages should only have on instance of tutorial name and skill aquired at the top of the page.

**Comment by inertia186** [comment]
Addressed in #226

**Comment by relativityboy** [comment]
Closed in #241
