### ISSUE TITLE
DP: Eval & add Java SC2 lib to community section - 2

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal#236]
Consider adding this lib to communities section
https://github.com/hapramp/steemconnect4j

(Lib was first mentioned in #225 comments

**AC**
- [x] lib is evaluated for addition.
- [x] Lib is added, or not. If not, comment titled `# Results` explaining why

**Comment by feruzm** [comment]
# Results

I did evaluate this Java library and I think this does look functional library and actively being developed. I would consider adding this library. https://github.com/hapramp/steemconnect4j
