### ISSUE TITLE
DP: Glossary: Additional Glossary terms

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal#255]
As a peruser of the DP, the glossary looks kinda light, and isn't thorough enough to carry on a conversation with a well rounded steem dev.

ex: broadcast operation, virtual operation, delegation, Mainnet

**AC**
- [x] add approx 10 more terms to the glossary
- [x] improve glossary definitions where appropriate.

**Comment by inertia186** [comment]
suggestion in standup `delegation`
