### ISSUE TITLE
Sign Up: Verification email doesn't arrive

### ISSUE THREAD

**Issue by Gifford-Productions** [steemit/devportal#258]
hi.
trying to signup on Steemit . Unfortunately the registration verification email that i should receive does not arrive. tried several times with several email addresses. also cleared cookies.done everything i could think of. anyone knows what to do or having same issues?

**Comment by TimCliff** [comment]
This is the wrong repository for signup related issues. The correct repository is https://github.com/steemit/faucet/.

If you open an issue there it would be helpful to open your browser’s developer console and see if there are any errors.
