### ISSUE TITLE
Community - Document Steem plugins

### ISSUE THREAD

**Issue by TimCliff** [steemit/devportal#269]
As a node operator, it would be beneficial to know what all of the available plugins are for steemd, what they do, and what dependencies exist. (For example, `account_history_api` needs either `account_history` or `account_history_rocksdb` enabled.)

- [x] Determine an appropriate section on the DP to add information about steemd node configurations.
- [x] List all of the available plugins that can be used in the config.ini file.
- [x] Provide a description of what the plugin does.
- [x] Provide a set of dependencies when other plugins are required to make a plugin work properly.

**Comment by inertia186** [comment]
Might be affacted by https://github.com/steemit/steem/issues/2648 in HF20.  The way I read this, when you're running a seed node, `config.ini`

```ini
enable-plugin = witness
```
... becomes ...

```ini
enable-plugin = rc
```

Or something.
