### ISSUE TITLE
Right Result, Bad HREF in Search Results

### ISSUE THREAD

**Issue by inertia186** [steemit/devportal#285]
The search query functionality works well enough.  It is able to locate pages that contain the requested keywords.

![image](https://user-images.githubusercontent.com/494368/43913724-afe8604e-9bba-11e8-9b2e-19a65e772c57.png)

The problem is that often these results do not link properly to the actual pages.  Some do.  A majority do not.

![image](https://user-images.githubusercontent.com/494368/43913960-57c77034-9bbb-11e8-9c61-e90a416c808c.png)

The link in the above example would lead to `/#tutorials-recipesjussi-multiplexer`, but the actual link should be `/tutorials-recipes/jussi-multiplexer`.

**Comment by roboza** [comment]
Changed the URL that gets used for search results.

**Comment by relativityboy** [comment]
@roboza - I don't see a PR.
