### ISSUE TITLE
DP: Mark account_history_api.get_transaction as deprecated

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal#291]
As a developer, I want to know what methods in the api are non-functional/deprecated so that I don't waste my time coding against stuff that doesn't work.

**AC**
- [ ] mark `account_history_api.get_transaction` as deprecated.
- [x] find other methods that are non-functional/deprecated and mark them as such

**Comment by inertia186** [comment]
We should also mark the `account_create_with_delegation` operation as deprecated in HF20.
