### ISSUE TITLE
Tutorials: Meta - Add standard language for Mainnet, Testnet, Etcnet

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal#298]
As a student developer I want to have a clear, easy to understand way to know *which* blockchain the tutorial connects to by default _so that I can know which credentials to use, and whether or not I should use restraint when performing actions._

**Supporting Materials**
Loosely Related: #159

**AC**
- [ ] create a standard visual layout and set of language that clearly state which blockchain the tutorial will connect to by default. In another story, this is to be implemented across all tutorials that will be hosted on the DP.
- [ ] add this standard in `# Results` and in the tutorial standards document

**Comment by relativityboy** [comment]
Add in results that we should avoid automation

**Comment by relativityboy** [comment]
# Results

## Proposal
List the connection, the main api call, accounts & keys used or needed, and if the tutorial is about getting or setting information on the blockchain. *please note, the `create one` would be a link to a tutorial on creating accounts, or link to an as-yet nonexistent account creation tool*

**At a glance**

| | | |
| :---------- | :--- | :--- |
| **connection** | Mainnet | main blockchain
| **method** | block_api.get_block | gets information
| **accounts** | none | |
| **keys required** | none
**At a glance**

| | | |
| :---------- | :--- | :--- |
| **connection** | Mainnet | main blockchain
| **method** | condenser_api.get_account_bandwidth | gets information
| **accounts** | @ned | |
| **keys required** | none


**At a glance**

| | | |
| :---------- | :--- | :--- |
| **connection** | testnet.steem.vc | test blockchain
| **method** | condenser_api.broadcast_transaction | sets information
| **operation** | vote | votes for content
| **accounts** | demo1, demo2, **or** [create one]() |
| **keys required** | posting | 

**At a glance**

| | | |
| :---------- | :--- | :--- |
| **connection** | testnet.steemitdev.com | test blockchain
| **method** | condenser_api.broadcast_transaction | sets information
| **operation** | comment | adds a comment or post
| **accounts** | demo1, demo2, **or** [create one]() |
| **keys required** | posting |

**Comment by inertia186** [comment]
That looks pretty good.
