### ISSUE TITLE
DP: Community: HF20: Add witness_set_properties - broadcast op to api methods

### ISSUE THREAD

**Issue by roelandp** [steemit/devportal#311]
Just like 2 other issues related to HF20 documentation 
- #296 
- #289 

for completeness sake added this issue to be complete about new HF methods, in this case the `witness_set_properties` - operation which takes the `current_owner_block_signing_key` as authorization and has the set of keys which can be set after HF20 sets in: 

- account_creation_fee
- account_subsidy_budget
- account_subsidy_decay
- maximum_block_size
- sbd_interest_rate
- sbd_exchange_rate
- url
- new_signing_key

https://github.com/steemit/steem/blob/master/doc/witness_parameters.md

**AC**

- [ ] `witness_set_properties` to `_data/apidefinitions/broadcast_ops.yml`

**Comment by therealwolf42** [comment]
Previously, we used `block_signing_key`. Is this replaced by `new_signing_key` for `witness_set_properties`?

**Comment by inertia186** [comment]
Closed via https://github.com/steemit/devportal/pull/382
