### ISSUE TITLE
Deploy - 6.1 - broadcast_transaction_synchronous documentation removal

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal#330]
Getting #329 into production

**Comment by roboza** [comment]
Html rendered in tutorial:

## Javascript Tutorials
1. grant_active_permission
```5. Broadcast operation<a name=”broadcast></a>```
2. grant_posting_permission
```5. Broadcast operation<a name=”broadcast></a>```
3. grant_action_permission, submit_post, search_accounts localhost link not working
```After a few moments, the server should be running at http://localhost:3000/```
4. There are several tutorials not making use of `configuration.js` import
5. set_withdraw_route instructions at bottom differ from other tutorials

## Python Tutorials
1. Python getting started tutorial brokwn link
```To get started with our Python tutorials, checkout our first tutorial here.```

## Ruby Tutorials
5. Tutorials overview ruby
 1. Missing description for tutorial `RB: Edit Content Patching`
 2. Tutorial submit_comment_reply has broken links to transactions on dsteem

**Comment by relativityboy** [comment]
@roboza - Nice! 3 bugs? One for each repo?
Regarding a couple notations:

> There are several tutorials not making use of configuration.js import
Some tutorials, the first three... weren't supposed to use our configurations because we want to make things very clear when people are beginning their journey. Others could use enumerating here if you have that info. We should probably skip adding the others as part of the bug since it's more a migration... 

> Missing description for tutorial RB: Edit Content Patching
I know that particular tutorial also creates some bad formatting when it's brought into the DP, the description line is mistakenly started with `###`.
