### ISSUE TITLE
DP: New sitemap

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal#360]
The amount of information on the devportal has increased dramatically since the last time the site map was updated. As a developer I want to be able to find the information I need quickly and with ease _so that I can learn and solve my business's problems with Steem_.

**Consider** 
* Steem Basics section
* Improved Getting Started section
* Steemit specific section (with steemit resources, etc?)

**AC**
- [x] create a new sitemap that makes it easier for new users, business users, and experienced devs to get the information they need quickly.
- [x] communicate changes publicly and to all teams
- [x] incorporate internal and community feedback.
- [x] in `# Results` comment describe the above

**Comment by TimCliff** [comment]
A few suggestions:
- The introduction page should clearly and concisely tell a new visitor where to go to find whatever they are looking for.
- I suggest removing the "Quick Start" section and just making sure all of the necessary information that a visitor needs to find what they need is in the introduction section.
- The "AppBase API" section should be renamed to "Blockchain API"
- There should be a section for steemd nodes, which includes: Information on connecting to public nodes, instructions for launching private nodes, all documentation for steemd node operation including configuration values.
- There should be a "Libraries" section where developers can find documentation for whichever libraries they want to use (Steem-JS, SteemPython, SteemRuby, etc.)
- There should be a new section for "Testnet"
- The "Sharing & Help" information should be renamed to "Developer Help" and should be it's own section.
- It would be nice if going to sections like the current introduction page didn't require two clicks to get to the page (Introduction -> Welcome to Steem).

**Comment by relativityboy** [comment]
* INTRODUCTION
* GETTING STARTED
  **What do you want to do?** (A section has many links to other parts of the site)
  * LEARN BASIC STEEM CONCEPTS (baby recipes section - new super basics)
  * APP DEVELOPER (js / py / ruby)
  * HOST A STEEM NODE
  * SOLVE A MORE COMPLEX PROBLEM (recipes)
  * SOLVE A BUSINESS PROBLEM (new section)
* TUTORIALS
* TESTNET 
  what is a testnet, list of steemit testnets & purpose, accessing with libs, firing up a node, launching your own
* STEEMD
  _optional_ - launch a steemd node. why
* SERVICES
  Clean this section up. Standardize presentation. Description of each and that devs are encouraged to host their own and why. (Possible links to 00 recipe described below)
* RECIPES
  Like current, but new 00 recipe that describes the typical stages an application will go through, and the resources / app stack they might use in each stage
* API
* PUBLIC NODES
* HIVEMIND 
  _optional_ depending on outcome of various things, description of it, how to use it. Link to all different locations where it's used. Encouragement to develop with it and contribute source code to it.
* RESOURCES
* EXCHANGES
  Guide exchanges through the process of setting up, incl some recommended processes for account creation if they're going to do that, and tools they should use for it.
* GLOSSARY

**Comment by roboza** [comment]
I like it. I think you have broken it up into more logical sections. Will be easier to find stuff.

**Comment by inertia186** [comment]
This is perfectly cromulent.

**Comment by relativityboy** [comment]
Calling this acceptable.
