### ISSUE TITLE
DP: Document Transaction polling API

### ISSUE THREAD

**Issue by TimCliff** [steemit/devportal#361]
In Steem issue https://github.com/steemit/steem/issues/2458, a new Transaction polling API was added. This new API should be documented in the dev portal.

- [ ] Document the plugins that are needed to enable this API on a steemd node.
- [ ] Add a new section in "APPBASE API" for any new method prefixes that were added.
- [ ] Add new API definitions in the "APPBASE API" section for the new method(s) that were added.

**Comment by inertia186** [comment]
To help implement this issue, I am using the following tintoy ref [`ed1ca68`](https://gist.github.com/inertia186/b88e7bfff8862858e54c59392e2bce20).

```bash
# Start the tintoy tag with transaction-status-api enabled ...
docker run -d -p 8090:8090 inertia/tintoy:transaction-status-api

# After waiting for the node to fully sych, check list of methods ...
curl -s --data '{"jsonrpc":"2.0", "method":"jsonrpc.get_methods", "id":1}' http://localhost:8090 | jq

# If we see transaction_status_api.find_transaction, we're ready to test ...
curl -s --data '{"jsonrpc":"2.0", "method":"transaction_status_api.find_transaction", "params": {"id": "0000000000000000000000000000000000000000"}, "id":1}' http://localhost:8090 | jq
```

#### Expected result:

```json
{
  "jsonrpc": "2.0",
  "result": {
    "status": "unknown"
  },
  "id": 1
}
```
