### ISSUE TITLE
Create Appbase API page

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal#37]
Document all Appbase API methods.

A quickref was created - though this should not be considered authoritative, all methods described should be validated for correctness: https://steemit.com/appbase/@holger80/api-methods-list-for-appbase

**AC**
- [x] Set of yml files, one for each method prefix (eg `database_api`, `block_api`)
- [x] Contents of each yml file 1: describes the context and purpose of the resources at that prefix
- [x] Contents of each yml file 2: a prefix specific list of (api method, parameter json, expected response json, purpose)
- [x] Contents of each yml file 3: each item in the prefix-specific list should be hash-linkable (suggest using `<api prefix>.<api method>`
- [ ] Create page for Appbase API Definitions (AAP) 
- [ ] AAP: List of common properties of request & response with definitions at the top
- [ ] AAP: Renders each yml file in a nicely formatted fashion, similar to glossary page.
- [ ] AAP: optional - JSON on the page is prettier formatted, regardless of formatting in YML file.

**Comment by TimCliff** [comment]
I don’t have permission to assign issues, but I can work on this.

**Comment by relativityboy** [comment]
FYI, it's possible to transform an object from the yml files into a json string and then highlight it with the following codeblock in the jekyll-liquid templating engine. Honestly it looses impact without pretty-printing and the huge amount of padding around the codblocks makes me think we should stick with the ` | jsonify` filter for now.

```
{% highlight json %}
{{method.expected_response_json | jsonify }}
{% endhighlight %}
```

**Comment by TimCliff** [comment]
@relativityboy I submitted PR https://github.com/steemit/devportal/pull/43. Please review and let me know what you think.

There are two areas that I think could still use some improvement - either in this PR or as a later enhancement:
- The styling/formatting. Let me know if you have any tips/suggestions for this.
- The method descriptions. I did my best to find info in the existing documentation, but for a lot of methods there wasn't much to go off of, so they are somewhat vague.

**Comment by relativityboy** [comment]
The last required AC was not met, but due to dev capacity, and in appreciation for @TimCliff's work we'll add _AAP: List of common properties of request & response with definitions at the top_ in a different issue.
