### ISSUE TITLE
Steemd plugin documentation

### ISSUE THREAD

**Issue by TimCliff** [steemit/devportal#371]
In issue https://github.com/steemit/devportal/issues/269, documentation was created for steemd plugins. The page with the info is here: https://developers.steem.io/tutorials-recipes/plugin_and_api_list

A few items of feedback:
- I cannot find a link to the plugin list in the menu
- The plugins that are listed on the page do not use the same names as what is needed in the config.ini file when enabling the plugin
- The dependencies are not clearly documented. For example, if I want to run `account_history_api`, I need to have either `account_history` or `account_history_rocksdb` enabled for it to work.

Suggested changes:
- [ ] Add a link to the plugins in the menu
- [ ] Clearly define what plugin name needs to be enabled within the config.ini file in order for the plugin to be turned on
- [ ] Review all dependencies and ensure they are documented appropriately

**Comment by inertia186** [comment]
I think someone misunderstood the requirements.  The plugin-to-repo dependencies are listed when the original requirements for #269 wanted plugin-to-plugin dependencies.

**Comment by inertia186** [comment]
This is how I'd go about it:

https://github.com/steemit/devportal/blob/8e073648e1576e695ed8c369592b7e2686ff274e/_tutorials-recipes/plugin-and-api-list.md
