### ISSUE TITLE
DP: Update getting started section - spike

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal#375]
It's confusing.

**AC**
- [x] figure out what should be on it, categorize based on dev/exchange/crypto holder/blockchain geek/etc
- [x] execute on the 1st item if at all possible. Otherwise create stories and put refs to them and why chose in `# Results` comment.

**Comment by relativityboy** [comment]
# Results 

A rough outline is available in this [comment](https://github.com/steemit/devportal/issues/360#issuecomment-439288308) and a branch [375-getting-started-page](https://github.com/steemit/devportal/tree/375-getting-started-page) has been created with base file & url changes.

**Comment by relativityboy** [comment]
Page currently looks like - <img width="551" alt="screen shot 2018-11-16 at 1 58 11 pm" src="https://user-images.githubusercontent.com/599528/48644291-be850900-e9a7-11e8-902f-cfbece1758a2.png">

**Comment by inertia186** [comment]
LGTM
