### ISSUE TITLE
Recipe: Document Transaction polling API

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal#384]
See #361 

**AC**

- [ ] Create a recipe or tutorial demonstrating how to use the new API method(s)

**Comment by TimCliff** [comment]
Suggested user story:
As a developer, I would like to be able to submit a transaction to the blockchain, and then use the new transaction polling API to determine the status of the transaction. The recipe should include a `switch` with a `case` statement for each possible transaction status, and output a string based on the current status of the transaction. It would be expected that the developer fill in whatever logic they want to use based on the different transaction statuses inside the switch.
