### ISSUE TITLE
Determine first set of JS tutorials

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal#40]
AC:
- [x] A list of tutorials and website appropriate descriptions in comments below.
- [x] Tutorials should be listed in order of difficulty.
- [x] A full set of tutorials will at a minimum replicate the api-call functionality of steemit.com.
- [x] One rollup comment labeled *Results* with a list of all the tutorial names. - This list is in "suggested order"

**Comment by feruzm** [comment]
Here are the list of 21 tutorials which I think should give any new developer advanced level of knowledge on how to build apps on top of Steem.

0. Get post list from different category (trending, hot, active, etc.)
1. Get post content and details
2. Get voters list on post/comment
3. Get comments of post
4. Get comments of account
5. Get replies of account
6. Submit a post
7. Submit a comment/reply
8. Search accounts
9. Search tags
10.  Vote post/comment (upvote, downvote)
11. Get followers and followings list of user
12. Follow another user (follow, unfollow)
13. Transfer STEEM and SBD
14. Power up STEEM
15. Transfer STEEM and SBD to savings balance
16. Convert SBD to STEEM 
17. Power down STEEM
18. Delegate STEEM POWER
19. Grant posting permission to another account (social activity)
20. Grant active permission to another account (funds activity)

**Comment by roboza** [comment]
21. Getting relevant account information (Power, value, balances etc)

**Comment by inertia186** [comment]
18a. Get delegations by user

**Comment by inertia186** [comment]
7a. Edit post/comment/reply using `diff_match_patch`.

**Comment by inertia186** [comment]
2b. Claim rewards

**Comment by inertia186** [comment]
12b. Reblogging post.

**Comment by inertia186** [comment]
8b. Interpreting account reputation.

**Comment by inertia186** [comment]
22. Witness listing/voting/unvoting

**Comment by feruzm** [comment]
**Results**

1. Get post list from different category (trending, hot, active, etc.)
2. Get post content and details
3. Get voters list on post/comment
4. Get comments of post
5. Get comments of account
6. Get replies of account
7. Submit a post
8. Submit a comment/reply
9. Edit post/comment/reply using diff_match_patch.
10. Reblogging post.
11. Search accounts
12. Search tags
13.  Vote post/comment (upvote, downvote)
14. Get followers and followings list of user
15. Follow another user (follow, unfollow)
16. Interpreting account reputation.
17. Claim rewards
18. Transfer STEEM and SBD
19. Power up STEEM
20. Transfer STEEM and SBD to savings balance
21. Convert SBD to STEEM 
22. Power down STEEM
23. Witness listing/voting/unvoting
24. Delegate STEEM POWER
25. Get delegations by user
26. Grant posting permission to another account (social activity)
27. Grant active permission to another account (funds activity)

---
* Additional tutorials can be around `sbds` and `hivemind`, once those products are production ready

**Comment by relativityboy** [comment]
Nice job @feruzm @roboza @inertia186 - this story is complete. We're going to have fun with all these tutorials.
