### ISSUE TITLE
Create stories for each tutorial defined in #40

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal#41]
Tutorials derived from output of #40 
A snippet from the  _raison de être_ parts of each tutorial, with and explanation.
This content should probably be cloned from a `.md` file in the tutorial itself.

**AC**
- [x] A well defined story for each tutorial defined in #40 has been created within the devportal repo and added to the backlock
- [x] Each story's name starts with `JS-T: `

**Comment by TimCliff** [comment]
@relativityboy here are some snippets from @drov0 that may be helpful.

https://github.com/drov0/steemsnippets

**Comment by relativityboy** [comment]
Nicely Done
