### ISSUE TITLE
I am not receiving TRX rewards

### ISSUE THREAD

**Issue by Wnfdiary** [steemit/devportal#471]
Hello,

My TRX rewards were working great, but the last two claims came without the reward. I didn't change anything with my wallet, so I don't know where is the catch. My Steem TRX wallet is connected with the Tron link wallet. However, I could see TRX share before claiming it, but after the claim, it didn't get to my wallet.

My Steem acc @wnfdiary
My TRX wallet: TFAuT7nbTMJ1tU8J438LmQGwVPUUvcwwzj

Thank you for any help

**Comment by Wnfdiary** [comment]
Here I got a new TRX reward but didn't get to my wallet again.
![Untitled-1](https://user-images.githubusercontent.com/41181226/114028482-ceebf600-9878-11eb-97f1-61dceb26f926.jpg)
![Untitled-2](https://user-images.githubusercontent.com/41181226/114028481-cdbac900-9878-11eb-8088-1c047f8c2cd4.jpg)

Thank you for help

**Comment by ety001** [comment]
Hi, @Wnfdiary 
The official Tron account which is used to send trx is out of balance. 
The application of fund is in progress.
Please be patient.

**Comment by Wnfdiary** [comment]
> Hi, @Wnfdiary
> The official Tron account which is used to send trx is out of balance.
> The application of fund is in progress.
> Please be patient.

I see. Thank you very much for explaining me. I am relieved now when I know it's not my fault or something. Have a nice day.
