### ISSUE TITLE
Ruby Tutorials

### ISSUE THREAD

**Issue by inertia186** [steemit/devportal#56]
To familiarize myself with the tutorials writing process, I've added some initial `ruby` tutorials.

**AC**

- [x] Sync up current ruby tutorials branch so that it matches existing tutorials JS, where applicable.
- [x] Add steps to clone the repo to access related ruby tutorial `.rb` files.

**Comment by relativityboy** [comment]
We should point this and put some AC on it so we can review and determine if it's suitable for production.
