### ISSUE TITLE
Evaluate - Document testnet story and create executable stories

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal#62]
The testnet is up. Evaluate the resources contained in https://github.com/steemit/steempunks/issues/274 and create a set of stories for putting testnet documentation into the developer portal.

**Notes**
Guidelines for stories. General testnet documentation should be language agnostic where possible.

**AC**
- [x] list of stories in a comment labeled *Results* with acceptance criteria as sub-bullets
- [x] each story created, and references this story, and the above 274 in its description

**Comment by feruzm** [comment]
Testnet has 2 parts:

1. Creating usage of existing testnets and document differences
2. Document how to create Testnet instance of Steem for advanced users

**Comment by feruzm** [comment]
**Results**

* Creating joining existing official testnet and document differences from main net
* Document how to create Custom Testnet instance of Steem for advanced users

Relevant issue is #74 and outcome of this will be PRed on that issue
