### ISSUE TITLE
Gather testnet specific tools/front-ends

### ISSUE THREAD

**Issue by inertia186** [steemit/devportal#73]
Need a section that lists any possible third-party tools that might have popped up like a steemdb or steemd versions pointing at a testnet, list them in a table.

**AC**

- [x] each testnet gets its own testnet_id (use the first seven characters of the chain id)
- [x] links to these front-ends live in the .yml
- [x] add a document iterates and presents the .yml as its own page

**Comment by inertia186** [comment]
wraps up all known testnet tools and endpoints, for the moment 6bbf52295dd4ce9fc9e2627ab3dcd159c0979a1e

**Comment by relativityboy** [comment]
@inertia186 should we create an issue for moving the current testnet documentation onto the testnet page with this info, and updating the testnet primary menu link to point to said page?
