### ISSUE TITLE
Document Creating Testnet instance of Steem

### ISSUE THREAD

**Issue by feruzm** [steemit/devportal#74]
Document how to create Testnet instance of Steem for advanced users...

AC

- [x] Tutorial should have clear step by step guidance on running Testnet
- [x] Changing parameters
- [x] Server specifics, hosting testnet
- [x] Additional details on how to allow API or getting started with Testnet usage similar to this: https://github.com/steemit/devportal/issues/62 
   - [x] Description of official testnet

**Comment by relativityboy** [comment]
@feruzm - it looks good as far as it goes.
@inertia186 - would you check out this branch and move the language to "English Developer Standard"?
