### ISSUE TITLE
Create Contributors.md file to explain guidelines and contributing to the Devportal

### ISSUE THREAD

**Issue by roboza** [steemit/devportal#75]
Add contributors section to Devportal to explain best practices and how to contribute tutorials and information to the Devportal.

**AC**

- [x] Add Contributors section
- [x] Add Contributors nav item to top of navigation
- [x] Add Syntax Highlighter/prettifier guidelines

**Comment by relativityboy** [comment]
@roboza you may find this very useful https://github.com/steemit/steempunks/tree/master/github_templates
