### ISSUE TITLE
Web: Tutorial for client signing of transaction - no steemconnect

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal#76]
**AC**
 - [x] put readme for steemit/devportal-tutorials-js#6 into website in same manner as those already present
- [x] menu item on tutorials page just after steemconnect with appropriate description

**Comment by inertia186** [comment]
While css class `right-section-title` is causing issues, rather than allow that to block this item, I've set the section css classes to `static-right-section-title`.
